# Generated by Django 4.2.13 on 2024-06-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
