# Generated by Django 4.2.13 on 2024-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_products_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="public",
            field=models.BooleanField(),
        ),
    ]
