# Generated by Django 4.2.13 on 2024-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_products_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
